Javascript/javascript1/week3
Poorooshka/hyf-homework pull request #7
Opened 2020-11-13 16:25 UTC by Poorooshka

2020-11-14 12:25 UTC, aina21 requested changes
you

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week1/Dog_Age.html
> +        const dogYearOfBirth = 2020;
try to not write javascript code in HTML file :)

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week1/Dog_Age.html
> +<!Doctype html>
you should remove change for  not related files from PR, to avoid conflict

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week1/Future_Age.html
> +<!DOCTYPE html>
remove change for this file as well

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week1/House_Price.html
> +<!DOCTYPE html>
same

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week1/Startup_Name.html
> +<!DOCTYPE html>
you should only have week3 files in this PR

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week3/Javascript1_Week3.js
> +  function findIndex(nameToRemove) {
findIndex is a function of javascript that I think you will learn more about in js2. 
try to avoid the name of the javascript methods or keywords.

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week3/Javascript1_Week3.js
> +"use strict";
one time on top of the file is enough :+1:

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week3/Javascript1_Week3.js
> +
I think you miss saveNote function

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week3/Javascript1_Week3.js
> +      const noteIndex = i;
why you need this variable? you can remove directly here

2020-11-14 12:25 UTC, aina21 commented on javascript/javascript1/week3/Javascript1_Week3.js
> +  removedNotes = notes.splice(noteIndex, 1)
noteindex is not defined outside of the if-scope

2020-11-15 08:03 UTC, Poorooshka commented on javascript/javascript1/week3/Javascript1_Week3.js
> +
I don't quite understand what you mean?

2020-11-22 10:01 UTC, closed without merging